services:
    organizer-service:
        build:
            context: ./
            target: dev
        volumes:
            - .:/home/node/app
        restart: always
        env_file: .env
        networks:
            - organizer
        ports:
            - 3000:3000
        command: npm start

networks:
    organizer:
        driver: bridge
